# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

warnings_are_errors: false

# cache: packages
# sudo: false

addons:
  apt:
    packages:
      - libmpfr-dev
      - libnetcdf-dev

r_packages:
  - covr
  - testthat
  - devtools

after_success:
  - Rscript -e 'covr::codecov()'

